---
title: "Visualize and test qPCR results"
author: "Lucas Moitinho-Silva"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      code: hide
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
---


# Introduction

I will visualize and test qPCR results.

# Preparations

## Set global options

```{r style, echo = T, results="asis", cache=FALSE, message = F}
#v.01
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev=c("png",'pdf'),
               fig.height = 6,
               fig.width = 5 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
theme_set(theme_few(base_size = 14))

# Set seed for reproducibility
set.seed(13)

# Set output directory
d.out <- params$d.out
rm(params)
```


## Load libraries for the session

```{r}
library(magrittr)
library(ggplot2)
library(tidyverse)
library(readxl)
library(MASS)
```

## Import data
```{r}
qpcr <- "~/IKMB/projects/sport/data.clean/qpcr.tsv" %>% 
  read_tsv()
```



# Visualize

```{r}
ggplot(qpcr, aes(x = Group, y = Mean)) +
  geom_boxplot(coef=6) +
  geom_jitter(aes(color = ParticipantID, shape = Sex), size =2) +
  scale_y_log10() +
  theme(legend.position = "none") +
  labs ( y = "Mean DNA concentration")
```


# Do analysis
```{r}
qpcr %>% 
  wilcox.test(Mean ~ Group, data = .)
```
# Save to plot
```{r}
"qpcr.rds" %>% 
  paste0(d.out, "/", .) %>% 
  saveRDS(qpcr, .)
```



# Conclusion

# Session information

```{r}
sessionInfo()
```
