---
title: "Make PCA based on dietary data"
author: "Lucas Moitinho-Silva"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
  d.out: "./"
---


# Introduction

Make PCA based on dietary data.

# Preparations


## Set global options

```{r style, echo = T, results="asis", cache=FALSE, message = F}
#v.01
# Set knit global options
library("knitr")
options(digits = 2, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = TRUE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev=c("png",'pdf'),
               fig.height = 6,
               fig.width = 5 * golden_ratio,
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
theme_set(theme_few(base_size = 10))

# Set seed for reproducibility
set.seed(13)
# Color blind friendly pallet
cbp1 <- c("#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999")

scale_fill_discrete <- function(...) {
   scale_fill_manual(..., values = cbp1)
}
scale_colour_discrete <- function(...) {
  scale_colour_manual(..., values = cbp1)
}

# Set output directory
d.out <- params$d.out
rm(params)
```


## Load libraries for the session

```{r}
library(tidyverse)
library(factoextra)
```

## Import data
```{r}
diet <- "~/IKMB/projects/sport/data.clean/diet.tsv" %>% 
  read_tsv()
meta <- "~/IKMB/projects/sport/data.clean/sampling.data.tsv" %>% 
  read_tsv()
```

# Make PCA

## Prepare data
```{r}
to.pca <- diet %>% 
  select(-ParticipantID, -Date, -time, -status, -sample.number) %>% 
  column_to_rownames("Seq.ID")
to.pca <- to.pca[complete.cases(to.pca),]
```

## Calculate principal components
```{r}
res.pca <- prcomp(to.pca, scale = TRUE)
pca.explain <- fviz_eig(res.pca)
pca.explain +
  labs(title = "") +
  theme_set(theme_few(base_size = 10))
fviz_pca_ind(res.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
# ADD PCs to meta

pca <- res.pca$x[, c("PC1", "PC2")] %>% 
  data.frame() %>% 
  rownames_to_column("Seq.ID")
```

# Save the outputs

```{r}
"pca.rds" %>% 
  paste0(d.out, "/", .) %>% 
  saveRDS(pca, .)
```

# Session information

```{r}
sessionInfo()
```
